### ISSUE TITLE
So wheres the webpack integration

### ISSUE THREAD

**Issue by mikeerickson** [seeden/angular-es6#1]
Figured I would look how others are using Angular / ES6 and Webpack and stumbled across this archive.  The mention of web pack in the readme is all there is.

The source does not have ANY usage of web pack (other than including in package.son)

**Comment by Kepro** [comment]
in devDependencies     "webpack": "^1.12.11"
and look in https://github.com/seeden/angular-es6/tree/master/example
there is a webpack config

**Comment by seeden** [comment]
I understand your confusion. This module was "boilerplate" at the begining. It is the real npm module in this moment. I updated description and added better example. Please take a look on the documentation and the directory example as @Kepro  mentioned.
