### ISSUE TITLE
The example won't run successfully

### ISSUE THREAD

**Issue by harri2012** [seeden/angular-es6#2]
Great work, but the example won't run successfully. wait someone to fix it

**Comment by seeden** [comment]
Can you attach your stacktrace? Node version etc...

Thanks
Zlatko

**Comment by harri2012** [comment]
the `filters`, `services` directory isn't exist. and the controller `Main`'s `$inject` has a `user` service, it isn't exist too. these are not big problems, I've made it.
And an advice,  in development build, copy the `dev.html` and js bundle files in `build` directory, in production build, copy `index.html` and js bundle file in `dist` directory. I need this feature. sorry for my pool english.

**Comment by seeden** [comment]
You are right. I forgot to commit some example files :) Please try to use the latest version
